---

- hosts: all
  become: true
  tasks:

# Debian and Ubuntu hosts #

  - name: install apache2 and php packages for Debian and Ubuntu hosts
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

# Centos hosts #

  - name: install httpd and php packages for CentOS hosts
    dnf:
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"


