---

- hosts: all
  become: true
  tasks:

  - name: install updates (Centos)
    tags: always
    dnf: 
      update_only: yes
      update_cache: yes
    when:  ansible_distribution == "CentOS" 

  - name: install updates (Ubuntu and Debian)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

# Web Servers
#
- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 and php packages for Debian and Ubuntu hosts
    tags: apache,apache2,ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]


  - name: install httpd and php packages for CentOS hosts
    tags: apache,centos,httpd
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"
  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
    when: ansible_distribution == "CentOS"
  
  - name: start httpd (Centos)
    tags: apache,centos,httpd
    service: 
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "CentOS"

  - name: change e-mail address for admin
    tags: apache,centos,httpd
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin somebody@somewhere.net
    when: ansible_distribution == "CentOS"
    register: httpd

  - name: restart httpd (Centos)
    tags: apache,centos,httpd
    service:
      name: httpd
      state: restarted
    when: httpd.changed

  - name: open port 80 for httpd (Centos)
    firewalld:
      port: "80/tcp"
      state: enabled
      permanent: yes
      immediate: yes
    when: ansible_distribution == "CentOS"
#
# DB servers
#
- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (Centos)
    tags: db,mariadb,centos
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"
      
  - name: install mariadb package (Ubuntu and Debian)
    tags: db,mariadb,ubuntu,debian
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution  in ["Debian", "Ubuntu"]

#
# File servers
#
- hosts: file_servers
  become: true
  tasks:

  - name: install samba pkg on file server
    tags: samba
    package:
      name: samba
      state: latest
              

#
# Workstations
#
- hosts: workstations
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.12.1/terraform_1.12.1_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

