---

- hosts: all
  become: true
  tasks:

  - name: install updates (Centos)
    tags: always
    dnf: 
      update_only: yes
      update_cache: yes
    when:  ansible_distribution == "CentOS" 

  - name: install updates (Ubuntu and Debian)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

# Web Servers
#
- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 and php packages for Debian and Ubuntu hosts
    tags: apache,apache2,ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]


  - name: install httpd and php packages for CentOS hosts
    tags: apache,centos,httpd
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

#
# DB servers
#
- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (Centos)
    tags: db,mariadb,centos
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"
      
  - name: install mariadb package (Ubuntu and Debian)
    tags: db,mariadb,ubuntu,debian
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution  in ["Debian", "Ubuntu"]

#
# File servers
#
- hosts: file_servers
  become: true
  tasks:

  - name: install samba pkg on file server
    tags: samba
    package:
      name: samba
      state: latest
      
