---

- hosts: all
  become: true
  tasks:

  - name: install updates (Centos)
    dnf: 
      update_only: yes
      update_cache: yes
    when:  ansible_distribution == "CentOS" 

  - name: install updates (Ubuntu and Debian)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

# Web Servers
#
- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 and php packages for Debian and Ubuntu hosts
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]


  - name: install httpd and php packages for CentOS hosts
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (Centos)
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"
      
  - name: install mariadb package (Ubuntu and Debian)
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution  in ["Debian", "Ubuntu"]

#
# File servers
#
- hosts: file_servers
  become: true
  tasks:

  - name: install samba pkg on file server
    package:
      name: samba
      state: latest
      
