#--------------------------------------------------------#
# Web Servers
#

- name: install apache2 and php packages for Debian and Ubuntu hosts
  tags: apache,apache2,ubuntu
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution in ["Debian", "Ubuntu"]


- name: install httpd and php packages for CentOS hosts
  tags: apache,centos,httpd
  dnf:
    name:
      - httpd
      - php
    state: latest
  when: ansible_distribution == "CentOS"
- name: copy default html file for site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution == "CentOS"

- name: start httpd (Centos)
  tags: apache,centos,httpd
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution == "CentOS"

- name: change e-mail address for admin
  tags: apache,centos,httpd
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin somebody@somewhere.net
  when: ansible_distribution == "CentOS"
  register: httpd

- name: restart httpd (Centos)
  tags: apache,centos,httpd
  service:
    name: httpd
    state: restarted
  when: httpd.changed

- name: open port 80 for httpd (Centos)
  firewalld:
    port: "80/tcp"
    state: enabled
    permanent: yes
    immediate: yes
  when: ansible_distribution == "CentOS"


