#
# DB servers
#
- name: install mariadb package (Centos)
  tags: db,mariadb,centos
  dnf:
    name: mariadb
    state: latest
  when: ansible_distribution == "CentOS"

- name: install mariadb package (Ubuntu and Debian)
  tags: db,mariadb,ubuntu,debian
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution  in ["Debian", "Ubuntu"]

